# Generated by Django 3.2.9 on 2022-02-18 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='persona/avatar')),
                ('whatsapp', models.CharField(blank=True, max_length=15, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='persona/pdf')),
            ],
            options={
                'verbose_name_plural': 'Persona',
                'ordering': ['-apellido'],
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('codigo', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('skill', models.CharField(max_length=150)),
                ('nivel', models.IntegerField()),
                ('estado', models.BooleanField(default=True)),
                ('imagen', models.CharField(blank=True, max_length=350, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('video', models.CharField(blank=True, max_length=350, null=True)),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.persona')),
            ],
            options={
                'verbose_name_plural': 'Skill',
                'ordering': ['skill'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField()),
                ('imagen', models.CharField(blank=True, max_length=350, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.persona')),
            ],
            options={
                'verbose_name_plural': 'Post',
                'ordering': ['fecha'],
            },
        ),
    ]
